version: '1.0'

services:
  python-weather-service:
    build:
      context: ./weather-collection-service
    ports:
      - "5000:5000"
    volumes:
      - ./weather-collection-service:/app
    environment:
      - CONFIG_FILE=config.yaml
    depends_on:
      - kafka

  golang-etl-service:
    build:
      context: ./weather-etl-service
    volumes:
      - ./weather-etl-service:/app
    environment:
      - CONFIG_FILE=config.yaml
    depends_on:
      - kafka

  nodejs-api-service:
    build:
      context: ./weather-report-service
    ports:
      - "3000:3000"
    volumes:
      - ./weather-report-service:/app
    environment:
      - CONFIG_FILE=config/default.json
    depends_on:
      - kafka
      - mongodb

  kafka:
    image: wurstmeister/kafka:2.13-3.9.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"

  mongodb:
    image: mongo:8.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
